### ISSUE TITLE
Failed to activate the amdbutler package

### ISSUE THREAD

**Issue by steveoh** [agrc/atom-amdbutler#36]
[Enter steps to reproduce below:]
1. add a new package

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [amdbutler](https://github.com/agrc/atom-amdbutler) package, v1.0.1
### Stack Trace

Failed to activate the amdbutler package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at Object.module.exports.activate (/Users/sgourley/.atom/packages/amdbutler/lib/atom-amdbutler.js:39:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:801:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:30.3.0 find-and-replace:select-next (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:29.6.0 vim-mode:find (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  2x -0:29.4.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:29.2.0 vim-mode:repeat-search (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
     -0:28.6.0 vim-mode:change (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
     -0:18.1.0 core:cut (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:17.2.0 core:paste (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  4x -0:15.8.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:09.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:08.3.0 command-palette:toggle (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:08.1.0 blur (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:05.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.4.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:05.4.0 linter-eslint:fix-file (atom-text-editor.editor.vim-mode.insert-mode)
     -0:01.6.0 amdbutler:add (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:00.0 blur (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

**Comment by stdavis** [comment]
Did 1.0.3 fix this for you?

**Comment by steveoh** [comment]
yup
